#let abbrv = (
  "CXL": "Compute Express Link",
  "PMEM": "Persistent Memory",
  "ASLR": "Address Space Layout Randomization",
  "PCIe": "Peripheral Component Interconnect Express",
  "TLB": "Translation Lookaside Buffer",
  "SSD": "Solid State Disk",
  "NVM": "Non-volatile Memory",
  "PMDK": "Persistent Memory Development Kit",
  "DRAM": "Dynamic Random Access Memory",
  "DDR": "Double Data Rate",
  "KV": "Key value",
  "WAL": "Write Ahead Log",
  "DAX": "Direct Access",
  "FAMS": "Failure atomic msync()",
  "NT": "Non Temporal",
  "YCSB": "Yahoo! Cloud Serving Benchmark",
  "RPC": "Remote procedure call",  
)